export const SET_INITIAL_SELLER_PRODUCTS="SET_INITIAL_SELLER_PRODUCTS"
export const ACCOUNT_CREATED_SUCCESSFULLY="ACCOUNT_CREATED_SUCCESSFULLY"
export const SELLER_ALREADY_EXIST="SELLER_ALREADY_EXIST"
export const USER_CART_ITEMS="USER_CART_ITEMS"
export const SET_INITIAL_USER_PRODUCTS="SET_INITIAL_USER_PRODUCTS"
export const ITEM_ADDED="ITEM_ADDED"
export const ITEM_DELETED="ITEM_DELETED"
export const ITEM_ALREADY_IN_CART="ITEM_ALREADY_IN_CART"
export const ITEM_SEARCHED="ITEM_SEARCHED"
export const ITEM_REDIRECTION="ITEM_REDIRECTION"
export const USER_ADDRESS_STATUS="USER_ADDRESS_STATUS"
export const SET_INITIAL_LAST_ORDERS_PRODUCTS="SET_INITIAL_LAST_ORDERS_PRODUCTS"






